### ISSUE TITLE
User Story 12: Organized Dropdown for Categories

### ISSUE THREAD

**Issue by miriamdosantos** [miriamdosantos/Ferrie-Bakery#13]
*As a **user**, I can **explore categories through an organized dropdown menu in the navbar** so that **can easily navigate through the different product categories and subcategories.**

**Acceptance criteria**
- Given  the navbar, 
- When when a user hovers over it, t
- Then dropdowns for categories and subcategories are displayed.

### Tasks
- [ ] Subtask 1:Design dropdown menu
- [ ] Subtask 2: Organize categories and subcategories
- [ ] Subtask 3:Test responsiveness

**Points:** 6
