### ISSUE TITLE
User Story 14: Store Updates on Homepage

### ISSUE THREAD

**Issue by miriamdosantos** [miriamdosantos/Ferrie-Bakery#15]
*As a **user**, I can **discover store updates (news, promotions, or events) on the homepage** so that **stay informed about the latest news and offers from the store.**

**Acceptance criteria**
- Given the homepage,
- When  store updates are available,
- Then they are displayed in a highlighted section.

### Tasks
- [ ] Subtask 1:Add "Store Updates" section
- [ ] Subtask 2: Design layout.
- [ ] Subtask 3: Test dynamic fetching of updates

**Points:** 5
