### ISSUE TITLE
User Story 16 Product Reviews

### ISSUE THREAD

**Issue by miriamdosantos** [miriamdosantos/Ferrie-Bakery#17]
*As a **user**, I can **leave and view reviews on products** so that ** I can share my experience and learn from others.**.*

**Acceptance criteria**
- Given a user is on a product page,
- When they submit a review,
- Then the review should display on the product page.

]

### Tasks
- [ ] Subtask 1: Build review form.
- [ ] Subtask 2: Link reviews to products.
- [ ] Subtask 3:Test review functionality.

**Points:** 8
