### ISSUE TITLE
User Story 19: Secure and Functional Deployment

### ISSUE THREAD

**Issue by miriamdosantos** [miriamdosantos/Ferrie-Bakery#20]
As a **developer**, I can ** I can deploy the application securely and functionally in production (Heroku)** so that **users can access a reliable and live platform.**.

**Acceptance criteria**
- Given  the app is ready for production,
- When app is deployed to the production environment,
- Then the application is live, secure, and fully functional for users.

### Tasks
- [ ] Subtask 1:  Configure production environment
- [ ] Subtask 2: Perform final testing in production
- [ ] Subtask 3:Validate deployment process.

**Points:** 7
